"""Build hooks/art.ts from Monet's 'Woman with a Parasol' (public domain).

Usage: python make_art.py <path to w381.webp or any copy of the painting>
"""
import base64, io, os, sys
from PIL import Image

src = Image.open(sys.argv[1]).convert('RGB')
w, h = src.size
top = int(h * 0.06)
band = src.crop((0, top, w, top + w // 4))  # parasol, sky and the woman's head

def b64(im, fmt, **kw):
    buf = io.BytesIO()
    im.save(buf, fmt, **kw)
    return base64.b64encode(buf.getvalue()).decode()

jpeg = b64(band.resize((1200, 300), Image.LANCZOS), 'JPEG', quality=72)
png = b64(band.resize((480, 120), Image.LANCZOS), 'PNG', optimize=True)
svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 300" preserveAspectRatio="xMidYMid slice">'
       f'<image width="1200" height="300" preserveAspectRatio="xMidYMid slice" href="data:image/jpeg;base64,{jpeg}"/></svg>')
assert len(svg) <= 131072, f'svg too large: {len(svg)}'
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'hooks', 'art.ts')
with open(out, 'w', encoding='utf-8') as f:
    f.write('// Generated by tools/make_art.py from Claude Monet, Woman with a Parasol (1875), public domain.\n')
    f.write(f'export const svg = {svg!r}\n')
    f.write(f'export const png = "{png}"\n')
print('svg chars', len(svg), 'png b64 chars', len(png))
